
server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itdn_mall?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123qwe
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.itdn.mall.entity

#@Slf4j
logging:
  level:
    root: debug

#redis config start
redis:
  max:
    total: 20 #最大连接数
    idle: 10 #最大空闲数
  min:
    idle: 2 #最小空闲数
  test:
    #从jedis连接池获取连接时，校验并返回可用的连接
    borrow: true
    #把连接放回jedis连接池时，校验并返回可用的连接
    return: false
redis1:
  ip: 127.0.0.1
  port: 6379
redis2:
  ip: 127.0.0.1
  port: 6380
#redis config end
