server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    url: jdbc:mysql://192.168.2.100:3306/security?characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: developer
    password: 05bZ/OxTB:X+yd%1
  redis:
    host: 192.168.2.100
    port: 6379
    #password: 123456
    # Redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 5000

mybatis:
  mapper-locations: classpath:mapper/*.xml
